### ISSUE TITLE
Feature Request: Use system-configured timezone and format to display time

### ISSUE THREAD

**Issue by juarezr** [xynium/moonphases#1]
## Feature Request: Use system-configured timezone to display time

Some features that would turn it very appealing:

### Use system-configured timezone to display time

- Currently, it only shows time in the UTC Timezone.
- It would be better if the time follows the system-configured timezone and format.
  - Thus, there would be no need to display the timezone. 

### Add settings for configuring the date/time format

Additionally, it could also have some options in settings for:
  - Time position:
    - [X] On the left
    - [ ] On the right
    - [ ] Hidden
  - Time/Date Format ( [like this](https://extensions.gnome.org/extension/4655/date-menu-formatter/) )
    - [X] System default.
    - [ ] Custom: [ HH':'MM ]
  

### Copy menu items to the clipboard on click

- Currently, nothing happens
-  It would be interesting to copy to the clipboard the info about: moon/sun/etc...

**Comment by xynium** [comment]
Hi,
I  had made this application for using in remote area (on a boat). All hour are utc, for simplicity, as other data are utc tide weather forcast etc...
My intention is to keep this extension simple and i got no time to add extra.
There is no use of internet and the algorithm is not very precise,when connected to internet it is possible to get much more precise data.
But it is another software, the code is open and you are free to make a fork.
